### PR TITLE
Support exotic attribute macros and arbitrary return types with `Termination` trait

### LINKED ISSUE #11: async fn main
Hi, 

It's common for `main` functions to look like this

```rs
#[tokio::main]
async fn main() -> anyhow::Result<()> {}
```

adding `#[fncmd]` to that doesn't work. is there planned support for that ?

### PR DESCRIPTION
**Pull request by midnightexigent**
Fixes #11 

I also took the liberty to fix the `cargo-clippy` warnings

### CODE REVIEW

**Comment by yuhr** [comment]
Sorry for being late, I'm going to take a look tomorrow.

**Comment by yuhr** [comment]
Hm, I can't get it to work. For instance I have tested with [`tokio`'s tutorial](https://tokio.rs/tokio/tutorial/hello-tokio), like this:

```rs
use fncmd::fncmd;
use mini_redis::{client, Result};

#[fncmd]
#[tokio::main]
async fn main() -> Result<()> {
	// Open a connection to the mini-redis address.
	let mut client = client::connect("127.0.0.1:6379").await?;

	// Set the key "hello" with value "world"
	client.set("hello", "world".into()).await?;

	// Get key "hello"
	let result = client.get("hello").await?;

	println!("got value from the server; result={:?}", result);

	Ok(())
}
```

Then it says:

```
error[E0277]: the trait bound `fncmd::Result: From<impl Future<Output = std::result::Result<(), Box<(dyn std::error::Error + Send + Sync + 'static)>>>>` is not satisfied
 --> src/main.rs:4:1
  |
4 | #[fncmd]
  | ^^^^^^^^ the trait `From<impl Future<Output = std::result::Result<(), Box<(dyn std::error::Error + Send + Sync + 'static)>>>>` is not implemented for `fncmd::Result`
  |
  = help: the following implementations were found:
            <fncmd::Result as From<()>>
            <fncmd::Result as From<std::result::Result<(), E>>>
  = note: required because of the requirements on the impl of `Into<fncmd::Result>` for `impl Future<Output = std::result::Result<(), Box<(dyn std::error::Error + Send + Sync + 'static)>>>`
  = note: this error originates in the attribute macro `fncmd` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the size for values of type `dyn std::error::Error + Send + Sync` cannot be known at compilation time
 --> src/main.rs:4:1
  |
4 | #[fncmd]
  | ^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `dyn std::error::Error + Send + Sync`
  = note: required because of the requirements on the impl of `std::error::Error` for `Box<dyn std::error::Error + Send + Sync>`
  = note: required because of the requirements on the impl of `From<fncmd::Result>` for `std::result::Result<(), Box<dyn std::error::Error + Send + Sync>>`
  = note: required because of the requirements on the impl of `Into<std::result::Result<(), Box<dyn std::error::Error + Send + Sync>>>` for `fncmd::Result`
  = note: this error originates in the attribute macro `fncmd` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
```

I don't have any idea how to solve this for now, let me investigate a while...

**Comment by mettz** [comment]
> Hm, I can't get it to work. For instance I have tested with [`tokio`'s tutorial](https://tokio.rs/tokio/tutorial/hello-tokio), like this:
> 
> ```rust
> use fncmd::fncmd;
> use mini_redis::{client, Result};
> 
> #[fncmd]
> #[tokio::main]
> async fn main() -> Result<()> {
> 	// Open a connection to the mini-redis address.
> 	let mut client = client::connect("127.0.0.1:6379").await?;
> 
> 	// Set the key "hello" with value "world"
> 	client.set("hello", "world".into()).await?;
> 
> 	// Get key "hello"
> 	let result = client.get("hello").await?;
> 
> 	println!("got value from the server; result={:?}", result);
> 
> 	Ok(())
> }
> ```
> 
> Then it says:
> 
> ```
> error[E0277]: the trait bound `fncmd::Result: From<impl Future<Output = std::result::Result<(), Box<(dyn std::error::Error + Send + Sync + 'static)>>>>` is not satisfied
>  --> src/main.rs:4:1
>   |
> 4 | #[fncmd]
>   | ^^^^^^^^ the trait `From<impl Future<Output = std::result::Result<(), Box<(dyn std::error::Error + Send + Sync + 'static)>>>>` is not implemented for `fncmd::Result`
>   |
>   = help: the following implementations were found:
>             <fncmd::Result as From<()>>
>             <fncmd::Result as From<std::result::Result<(), E>>>
>   = note: required because of the requirements on the impl of `Into<fncmd::Result>` for `impl Future<Output = std::result::Result<(), Box<(dyn std::error::Error + Send + Sync + 'static)>>>`
>   = note: this error originates in the attribute macro `fncmd` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error[E0277]: the size for values of type `dyn std::error::Error + Send + Sync` cannot be known at compilation time
>  --> src/main.rs:4:1
>   |
> 4 | #[fncmd]
>   | ^^^^^^^^ doesn't have a size known at compile-time
>   |
>   = help: the trait `Sized` is not implemented for `dyn std::error::Error + Send + Sync`
>   = note: required because of the requirements on the impl of `std::error::Error` for `Box<dyn std::error::Error + Send + Sync>`
>   = note: required because of the requirements on the impl of `From<fncmd::Result>` for `std::result::Result<(), Box<dyn std::error::Error + Send + Sync>>`
>   = note: required because of the requirements on the impl of `Into<std::result::Result<(), Box<dyn std::error::Error + Send + Sync>>>` for `fncmd::Result`
>   = note: this error originates in the attribute macro `fncmd` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> For more information about this error, try `rustc --explain E0277`.
> ```
> 
> I don't have any idea how to solve this for now, let me investigate a while...

I have already encountered this error in a similar situation when I tried to return an `anyhow::Result` from `main`. I think it'ss caused by this line since it declares its own return type (`fncmd::Result`) instead of using the one provided by the user.
https://github.com/yuhr/fncmd/blob/260b1b84038ec5d3987471c3470e197cde8dfc41/impl/src/models/fncmd.rs#L202
Though, I don't know if there is a better fix than just replace it with `#return_type`

**Comment by midnightexigent** [comment]
Yeah, I also noticed that, but I think the reason `#return_type` isn't used is to let sub-commands have different return types, right @yuhr ? 

I tried experimenting with some other ways to do it, here are some alternatives 

- Using [std::process::Termination](https://doc.rust-lang.org/std/process/trait.Termination.html)
- Using a trait instead of an intermediate type 
```rust
pub trait IntoResult<'a> {
	fn into_result(self) -> Result<(), Box<dyn std::error::Error + 'a>>;
}

impl<'a> IntoResult<'a> for () {
	fn into_result(self) -> Result<(), Box<dyn std::error::Error + 'a>> {
		Ok(())
	}
}

impl<'a, T, E: Into<Box<dyn std::error::Error + 'a>>> IntoResult<'a> for Result<T, E> {
	fn into_result(self) -> Result<(), Box<dyn std::error::Error + 'a>> {
		match self {
			Ok(_) => Ok(()),
			Err(err) => Err(err.into()),
		}
	}
}


// then we can add .into_result() at the appropriate places
// and the main function can now look like this
fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
	
}


```

**Comment by yuhr** [comment]
> Yeah, I also noticed that, but I think the reason `#return_type` isn't used is to let sub-commands have different return types, right @yuhr ?

Yes, so we have to abstract different return types somehow. Thank you for enumerating the alternatives, I was quite unsure what manner is the right direction. It seems `Termination` is meant to be the perfect solution for the problem here, instead of reinventing on our own.

**Comment by midnightexigent** [comment]
Yes, I've already experimented to make it work with `Termination`. If I remember correctly I ran into the following problem

```rust

// with the following functions
fn subcmd() { // returns ()
}
fn main() -> anyhow::Result<()> {
    Ok(())
}

// the following code is generated 
fn exec() -> impl Termination {
    match ... {
         _ =>  { main_body } 
         _ => { subcmd_body }
    }
}
```

Even tho both arms of the `match` block return an `impl Termination`, the generated code doesn't compile. It complains that the types returned in the `match` block aren't the same 

One workaround I tried is to return a `Box<dyn Termination>` and wrap the function bodies in `Box::new`, but then, it complained that `Box<dyn Termination>` doesn't implement the `Termination`  trait. I am sure there's a good way to go about it.. Maybe use an `enum` instead where all the variants implement `Termination` ? But then again, that loops back to using a custom type.. which is what we're trying to avoid

**Comment by yuhr** [comment]
By the way I've noticed the first thing we should consider is ordering of the attribute macros. From the tutorial I put the attribute macros in this order thoughtlessly:

```rs
#[fncmd]
#[tokio::main]
async fn main() { ... }
```

But this resulted in a wrong code for now:

```rs
async fn __fncmd_exec_impl(__fncmd_options: Option<__fncmd_options>) {
    let __fncmd_options { .. } = __fncmd_options.unwrap_or_else(|| {
        use fncmd::clap::Parser;
        __fncmd_options::parse()
    });
    {}
}
#[inline]
pub fn __fncmd_exec(__fncmd_options: Option<__fncmd_options>) -> fncmd::Result {
    __fncmd_exec_impl(__fncmd_options).into()
}
fn main() {
    let body = async { __fncmd_exec(None).into() };
    #[allow(clippy::expect_used)]
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("Failed building the Runtime")
        .block_on(body)
}
```

Oh, we need `#[tokio::main]` to be expanded before `#[fncmd]`, so the (temporarily) correct order I thought then is:

```rs
#[tokio::main]
#[fncmd]
async fn main() { ... }
```

Then we get:

```rs
fn __fncmd_exec_impl(__fncmd_options: Option<__fncmd_options>) {
    let __fncmd_options { .. } = __fncmd_options.unwrap_or_else(|| {
        use fncmd::clap::Parser;
        __fncmd_options::parse()
    });
    {
        let body = async {};
        #[allow(clippy::expect_used)]
        tokio::runtime::Builder::new_multi_thread()
            .enable_all()
            .build()
            .expect("Failed building the Runtime")
            .block_on(body);
    }
}
#[inline]
pub fn __fncmd_exec(__fncmd_options: Option<__fncmd_options>) -> fncmd::Result {
    __fncmd_exec_impl(__fncmd_options).into()
}
fn main() {
    __fncmd_exec(None).into()
}
```

This works well where I have no parameters. But if I have any:

```rs
#[tokio::main]
#[fncmd]
pub async fn main(hello: u32) { ... }
```

`rustc` says that `the main function cannot accept arguments`. It seems that Rust requires procedural macros to produce legal Rust code *for each* macroexpansion. We firstly need to remove and save parameters somewhere so that exotic attribute macros work correctly, and thus `#[fncmd]` must be attached as the most outer macro, since inner macros can't tell whether there're other attribute macros. Finally, the correct order will be:

```rs
#[fncmd]
#[tokio::main]
pub async fn main(hello: u32) { ... }
```

**Comment by yuhr** [comment]
Now it seems everything goes well. Could you check if this branch works for you, @midnightexigent?

**Comment by midnightexigent** [comment]
Yes ! I tested the example from tokio and it worked. Thanks!

```rust
use fncmd::fncmd;
use mini_redis::{client, Result};

#[fncmd]
#[tokio::main]
pub async fn main(
    /// the address
    #[opt(short, long, default_value = "127.0.0.1:6379")]
    addr: String,
) -> Result<()> {
    // Open a connection to the mini-redis address.
    let mut client = client::connect(addr).await?;

    // Set the key "hello" with value "world"
    client.set("hello", "world".into()).await?;

    // Get key "hello"
    let result = client.get("hello").await?;

    println!("got value from the server; result={:?}", result);

    Ok(())
}

```

**Comment by midnightexigent** [comment]
I upgraded `clap` and made a change to make `clippy` happy if it's fine by you

**Comment by yuhr** [comment]
Thank you a lot @midnightexigent, this wouldn't have become a thing without your work and advice!

**Pull request merged**
